

branches:
  # all branches
  only:
  - gh-pages
  - /.*/

# all jobs should enable the release flag for compiler optimizations
env:
  global:
  - WHITENOISE_RELEASE=True
  - PROTO_VERSION=3.11.4
  - TWINE_USERNAME=__token__

notifications:
  email: false

jobs:
  include:
  - name: Test Rust
    os: linux
    language: rust
    rust: stable
    script:
    # (1) Rust Validator -> Test & Build
    - cd validator-rust; cargo build --verbose --workspace;
    - cargo test --verbose --workspace;
    - cd ..
    # (2) Rust Runtime -> Test & Build
    - cd runtime-rust; cargo build --verbose --workspace;
    - cargo test --verbose --workspace;
    - cd ..;

    after_success:
    #
    # Build the documentation for gh-pages
    #
    - echo $TRAVIS_BRANCH;
    # switch to master after initial version
    #- if [ "$TRAVIS_BRANCH" == "develop" ]; then
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
        bash build_docs.sh;
      fi;
    # -------------------------------------------
    # Deploy the Rust documentation to
    # GitHub pages
    # - Triggered when the branch is "master"
    # -------------------------------------------
    deploy:
      provider: pages
      skip_cleanup: true
      local_dir: docs
      # Set in the settings page of your repository, as a secure variable
      github_token: $GITHUB_TOKEN
      keep_history: true
      target_branch: gh-pages
      on:
        branch: master # switch to master after initial version
        #branch: develop # switch to master after initial version
