name: Rust

on: [push]
#  #  branches: [ develop, 348-* ]
#  #pull_request:
#  #  branches: [ develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd ffi-rust; cargo build --verbose --workspace;
    - name: Run tests
      run: cd ffi-rust; cargo test --verbose --workspace;
