name: Rust

on: #[push, pull_request]
  push:
    branches: [348-action]
#     #pull_request:
#  #  branches: [ develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: github.ref == 'refs/heads/x348-action'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #
    - name: Build docs
      run: |
        bash scripts/build_docs.sh;
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
    #- name: Build
    #  #if: ${{ steps.extract_branch.outputs.branch }} == 'hello348-action'
    #  run: |
    #    cd ffi-rust;
    #    cargo build --verbose --workspace;
    #- name: Run tests
    #  if: ${{ steps.extract_branch.outputs.branch }} == 'hello348-action'
    #  run: |
    #    cd ffi-rust;
    #    cargo test --verbose --workspace;
