name: Rust

on:
  push:
    branches: [348-doc-fix]
  #pull_request:
  #  branches: [ develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd ffi-rust;
        cargo build --verbose --workspace;
    - name: Run tests
      run: |
        cd ffi-rust;
        cargo test --verbose --workspace;
  deploy:
    if: ${{ github.ref == '348-doc-fix' }}
    needs: build
    steps:
      run: |
        bash scripts/build_docs.sh;
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs # The folder the action should deploy.
