name: Rust

on: #[push, pull_request]
  push:
    branches: [348-action]
#     #pull_request:
#  #  branches: [ develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set the branch name
      shell: bash
      id: extract_branch
      run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
    - name: Build docs
      if: ${{ steps.extract_branch.outputs.branch }} == '348-action'
      run: |
        bash scripts/build_docs.sh;
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
    - name: Build
      if: {{ github.ref == 'ref/head/develop' }}
      run: |
        cd ffi-rust;
        cargo build --verbose --workspace;
    - name: Run tests
      if: {{ github.ref == 'ref/head/develop' }}
      run: |
        cd ffi-rust;
        cargo test --verbose --workspace;
